apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-microservice
  namespace: microservices
  labels:
    app: hello-world-microservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-world-microservice
  template:
    metadata:
      labels:
        app: hello-world-microservice
    spec:
      containers:
        - name: hello-world-microservice
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}