apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: generic-pipeline-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-builder
  triggers:
    - name: github-push
      bindings:
        - ref: github-push-binding
      template:
        ref: pipeline-trigger-template
      params:
        - name: pipeline-name
          value: $(body.repository.name)-pipeline
        - name: image
          value: docker.io/<dein-benutzer>/$(body.repository.name):latest
        - name: context-path
          value: $(body.repository.name)
        - name: dockerfile-path
          value: Dockerfile