apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-microservice-pipeline
  namespace: tekton
spec:
  serviceAccountName: tekton-builder
  workspaces:
    - name: source
  params:
    - name: image
      type: string
      description: The target image name
    - name: git-url
      type: string
      description: The Git repository URL
    - name: git-revision
      type: string
      description: The Git revision to checkout
      default: main
    - name: context-path
      type: string
      description: The path to the project directory within the workspace
      default: hello-world-microservice
    - name: dockerfile-path
      type: string
      description: The path to the Dockerfile relative to the context path
      default: Dockerfile
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: source
    - name: build-and-push
      taskRef:
        name: build-and-push-task
      runAfter:
        - fetch-repository
      params:
        - name: image
          value: $(params.image)
        - name: context-path
          value: $(params.context-path)
        - name: dockerfile-path
          value: $(params.dockerfile-path)
      workspaces:
        - name: source
          workspace: source